package sudoku;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import sudoku.buildlogic.SudokuBuildLogic;
import sudoku.userinterface.IUserInterfaceContract;
import sudoku.userinterface.UserInterfaceImpl;

import java.io.IOException;

public class SudokuApplication extends Application {
    /**
     * Interfaces (as View) for this project are prefixed with I and suffixed with uiImpl
     */
    private IUserInterfaceContract.View uiImpl;

    @Override
    public void start(Stage primaryStage) throws Exception{
        uiImpl = new UserInterfaceImpl(primaryStage);
        try {
            /**
             * The SudokuBuildLogic class contains the build logic and the code required to wire everything together. If the operation fails, we catch the exception.
             */
            SudokuBuildLogic.build(uiImpl);
        }catch (IOException e){
            e.printStackTrace();
            throw e;
        }
    }

    /**
     * Main class method automatically generated by the IDEA on creating project
     * @param args
     */
    public static void main(String[] args) {
        launch(args);
    }
}
